const mongoose = require('mongoose');

const staffSchema = new mongoose.Schema({
  first_name: { type: String, required: true },
  last_name: { type: String, required: true },
  other_names: String,
  gender: { type: String, required: true },
  dob: { type: Date, required: true },
  marital_status: { type: String, required: true },
  address: { type: String, required: true },
  phone: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  photo: String,
  designation: { type: String, required: true },
  department: { type: String, required: true },
  staff_type: { type: String, required: true },
  date_joined: { type: Date, required: true },
  qualification: { type: String, required: true },
  experience: String,
  previous_employer: String,
  specialization: String,
  id_type: String,
  id_number: String,
  id_upload: String,
  kin_name: String,
  kin_relationship: String,
  kin_phone: String,
  kin_address: String,
  bank_name: String,
  account_name: String,
  account_number: String,
  pension: String,
  tax_id: String,
  emergency_name: String,
  emergency_phone: String,
  emergency_relationship: String,
  login_email: { type: String, required: true, unique: true },
  login_password: { type: String, required: true },
  access_level: { type: String, required: true }
}, { timestamps: true });

module.exports = mongoose.model('Staff', staffSchema);
